# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T11:40:04+00:00



import argparse
import json
import os
from typing import *
from typing import Optional

from autogen.mcp.mcp_proxy import MCPProxy
from autogen.mcp.mcp_proxy.security import BaseSecurity
from fastapi import Query

app = MCPProxy(
    contact={
        'email': 'info@visualcrossing.com',
        'name': 'Visual Crossing Corporation',
        'url': 'https://www.visualcrossing.com/weather-api',
        'x-twitter': 'visualcrossing',
    },
    description='Weather Forecast and Historical Weather Data via RESTful API.',
    license={
        'name': 'Visual Crossing Weather API',
        'url': 'https://www.visualcrossing.com/weather-api',
    },
    termsOfService='https://www.visualcrossing.com/weather-services-terms',
    title='Visual Crossing Weather API',
    version='4.6',
    servers=[{'url': 'https://weather.visualcrossing.com'}],
)


@app.get(
    '/VisualCrossingWebServices/rest/services/timeline/{location}',
    description=""" Seamless access to daily and hourly historical and forecast weather data plus weather alerts, events and current conditions. """,
    tags=['weather_data_retrieval'],
)
def get_weather_data_timeline(
    location: str,
    content_type: Optional[str] = Query(None, alias='contentType'),
    unit_group: Optional[str] = Query(None, alias='unitGroup'),
    include: Optional[str] = None,
    lang: Optional[str] = None,
    key: str = ...,
):
    """
    Historical and Forecast Weather API
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/VisualCrossingWebServices/rest/services/timeline/{location}/{startdate}',
    description=""" Seamless access to daily and hourly historical and forecast weather data plus weather alerts, events and current conditions. """,
    tags=['weather_data_retrieval'],
)
def get_weather_history_forecast(
    location: str,
    startdate: str = ...,
    content_type: Optional[str] = Query(None, alias='contentType'),
    unit_group: Optional[str] = Query(None, alias='unitGroup'),
    include: Optional[str] = None,
    lang: Optional[str] = None,
    key: str = ...,
):
    """
    Historical and Forecast Weather API
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/VisualCrossingWebServices/rest/services/timeline/{location}/{startdate}/{enddate}',
    description=""" Seamless access to daily and hourly historical and forecast weather data plus weather alerts, events and current conditions. """,
    tags=['weather_data_retrieval'],
)
def fetch_weather_data_timeline(
    location: str,
    startdate: str = ...,
    enddate: str = ...,
    content_type: Optional[str] = Query(None, alias='contentType'),
    unit_group: Optional[str] = Query(None, alias='unitGroup'),
    include: Optional[str] = None,
    lang: Optional[str] = None,
    key: str = ...,
):
    """
    Historical and Forecast Weather API
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/VisualCrossingWebServices/rest/services/weatherdata/forecast',
    description=""" Provides access to weather forecast information. The forecast is available for up to 15 days at the hourly, 12 hour and daily summary level. """,
    tags=['weather_data_retrieval'],
)
def get_weather_forecast_api(
    send_as_datasource: Optional[bool] = Query(None, alias='sendAsDatasource'),
    allow_asynch: Optional[bool] = Query(None, alias='allowAsynch'),
    short_column_names: Optional[bool] = Query(None, alias='shortColumnNames'),
    locations: Optional[str] = None,
    aggregate_hours: Optional[str] = Query(None, alias='aggregateHours'),
    content_type: Optional[str] = Query(None, alias='contentType'),
    unit_group: Optional[str] = Query(None, alias='unitGroup'),
    key: Optional[str] = None,
):
    """
    Weather Forecast API
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/VisualCrossingWebServices/rest/services/weatherdata/history',
    description=""" The weather history data is suitable for retrieving hourly or daily historical weather records. """,
    tags=['weather_data_retrieval'],
)
def retrieve_historical_weather_records(
    max_distance: Optional[str] = Query(None, alias='maxDistance'),
    short_column_names: Optional[bool] = Query(None, alias='shortColumnNames'),
    end_date_time: Optional[str] = Query(None, alias='endDateTime'),
    aggregate_hours: Optional[str] = Query(None, alias='aggregateHours'),
    collect_station_contributions: Optional[bool] = Query(
        None, alias='collectStationContributions'
    ),
    start_date_time: Optional[str] = Query(None, alias='startDateTime'),
    max_stations: Optional[str] = Query(None, alias='maxStations'),
    allow_asynch: Optional[bool] = Query(None, alias='allowAsynch'),
    locations: Optional[str] = None,
    include_normals: Optional[bool] = Query(None, alias='includeNormals'),
    content_type: Optional[str] = Query(None, alias='contentType'),
    unit_group: Optional[str] = Query(None, alias='unitGroup'),
    key: Optional[str] = None,
):
    """
    Retrieves hourly or daily historical weather records.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="MCP Server")
    parser.add_argument(
        "transport",
        choices=["stdio", "sse", "streamable-http"],
        help="Transport mode (stdio, sse or streamable-http)",
    )
    args = parser.parse_args()

    if "CONFIG_PATH" in os.environ:
        config_path = os.environ["CONFIG_PATH"]
        app.load_configuration(config_path)

    if "CONFIG" in os.environ:
        config = os.environ["CONFIG"]
        app.load_configuration_from_string(config)

    if "SECURITY" in os.environ:
        security_params = BaseSecurity.parse_security_parameters_from_env(
            os.environ,
        )

        app.set_security_params(security_params)

    mcp_settings = json.loads(os.environ.get("MCP_SETTINGS", "{}"))

    app.get_mcp(**mcp_settings).run(transport=args.transport)
